# Generated by Django 4.0.3 on 2022-03-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quantiti',
            new_name='quantity',
        ),
    ]
